# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Udapeople Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test_and_scan_frontend:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      # - name: Install frontend dependencies
      #   run: |
      #     cd frontend
      #     npm install
      #     sudo npm install webpack -g
      # - name: Build frontend
      #   run: |
      #     cd frontend
      #     npm run build:prod
      # - name: Temporarily save build artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: dist
      #     path: ${{ github.workspace }}/frontend/dist/
      #     retention-days: 1
      - name: Test frontend
        run: |
          cd frontend
          npm test
      - name: Scan frontend
        run: |
          cd frontend
          npm audit fix --audit-level=critical --force
          npm audit --audit-level=critical

  push-to-dockerhub:
    runs-on: ubuntu-20.04
    needs: build_test_and_scan_frontend

    steps:
      - uses: actions/checkout@v2
      # - uses: actions/download-artifact@v1
      #   with:
      #     name: dist
      #     path: frontend/dist/
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Docker image
        run: |
          cd frontend
          docker build -t wache/udapeople-github-app:${{github.run_number}} .
      - name: Push Docker image
        run: |
          docker push wache/udapeople-github-app:${{github.run_number}}
